
* Table of Contents :toc:
- [[#info][Info]]
  - [[#todo][ToDo]]
- [[#setup][Setup]]
- [[#what-else][What else?]]

* Info
Allows for a One-Way Sync from Stremio to Simkl. Plan is to have a Two-Way Sync

*** Warning
Currently the sync will by default not update the list unless _SIMKL_BACKFILL_MODIFYLIST_ is set to true.

However there are some checks in place for backfilling:
 * List Update: Ignored if Simkl already marked as complete
 * List Update: Ignored if Simkl already has the item and _SIMKL_BACKFILL_MODIFYLIST_ is false
 * Watch History Update (Movie): Ignored if Simkl already marked as complete
 * Watch History Update (Show): Ignored if Simkl lastWatched is greater than Stremio

I plan on adding more checks to limit and only process necessary items:
 * If you have any more checks to recommend feel free to open an issue.

** ToDo
 * [X] Only sync actual diffs
 * [ ] Sync Lists from Simkl to Stremio
 * [ ] Sync History from Simkl to Stremio
 * [X] Sync Lists from Stremio to Simkl
 * [X] Sync History from Stremio to Simkl
 * [ ] Stremio listen to stream events and update Simkl live

* Setup

*** Build

#+begin_src bash
npm install
npm run build
#+end_src

*** Start
Start the program. Then go to http://localhost:7000/configure
#+begin_src bash
npm run start
#+end_src

*** Sync
The syncing will start the moment you finish your first watched episode. You can check the console for successfull syncs.
In case at some point syncing stops due to an invalid authKey restart stremio and watch another episode for now.
If it still fails open an issue with some details so I can check it out.

*** Options
Following Options are available:
#+begin_src env
SIMKL_BACKFILL_LISTSHOWS=true # Option if it should sync shows to simkl list on boot
SIMKL_BACKFILL_LISTMOVIES=true # Option if it should sync movies to simkl list on boot
SIMKL_BACKFILL_WATCHHISTORYSHOWS=true # Option if it should sync shows to simkl history on boot
SIMKL_BACKFILL_WATCHHISTORYMOVIES=true # Option if it should sync movies to simkl history on boot

# If this is enabled it will add shows and movies to the list, but also move them around on simkl using stremio as the leader.
SIMKL_BACKFILL_MODIFYLIST=false

# If this is enabled it will disregard specific watched episodes for shows, but instead mark all previous shows before the current as watched.
# Use this if you more often than not forget to mark episodes as watched.
SIMKL_BACKFILL_LASTEPISODEFILL=false

#+end_src

* What else?

The code is honestly a mess, but I believe that it would be worse of me to showcase a video of it working and then saying I need to clean up the code before pushing it to GitHub. At least in the meantime someone may make use of this.

It's currently a proof of concept. Depending on how much interest there is, I'll clean it up and not just have it workable.

Any pull requests are of course welcome.
