
* Table of Contents :toc:
- [[#info][Info]]
  - [[#todo][ToDo]]
- [[#setup][Setup]]
- [[#what-else][What else?]]

* Info
Allows for a One-Way Sync from Stremio to Simkl. Plan is to have a Two-Way Sync

*** Warning
Currently the sync will by default not update the list unless SIMKL BACKFILL MODIFYLIST is set to true.
This is mainly, since I haven't double-checked if everything works.

However there are some checks in place for backfilling:
 * Ignored if Simkl already marked as complete

I plan on adding more checks:
 * Stremio Date Checks to make sure diffs are managed correctly and only when necessary.
 * Simkl Date Checks to make sure diffs are managed correctly and only when necessary.
 * Watch Check based on if Stremio or Simkl is further along with show progress.

** ToDo
 * [-] Only sync actual diffs (partial)
 * [ ] Sync Lists from Simkl to Stremio
 * [ ] Sync History from Simkl to Stremio
 * [X] Sync Lists from Stremio to Simkl (Messy)
 * [X] Sync History from Stremio to Simkl (Messy)
 * [ ] Stremio listen to stream events and update Simkl live

* Setup

*** Build

#+begin_src bash
npm install
npm build
#+end_src

*** Start
Start the program. It will automatically generate a .env file and crash. Add your Stremio Credentials (these can be removed later on afaik). Then restart the application.
#+begin_src bash
npm start
#+end_src

*** Options
Following Options are available:
#+begin_src env

STREMIO_EMAIL=    # Fill this in manually
STREMIO_PASSWORD= # Fill this in manually
STREMIO_AUTHKEY=  # Not Necessary will be done automatically

SIMKL_CLIENTID=    # Not Necessary, but would appreciate it if you use your own Simkl Client
SIMKL_ACCESSTOKEN= # Not Necessary will be done automatically

# If these are enabled it will at minimum sync the watch history
SIMKL_BACKFILL_SHOWS=true # Option if it should sync shows to simkl on boot
SIMKL_BACKFILL_MOVIES=true # Option if it should sync movies to simkl on boot

# If this is enabled it will add shows and movies to the list, but also move them around on simkl using stremio as the leader.
SIMKL_BACKFILL_MODIFYLIST=false

# If this is enabled it will disregard specific watched episodes for shows, but instead mark all previous shows before the current as watched.
# Use this if you more often than not forget to mark episodes as watched.
SIMKL_BACKFILL_LASTEPISODEFILL=false

#+end_src

* What else?

The code is honestly a mess, but I believe that it would be worse of me to showcase a video of it working and then saying I need to clean up the code before pushing it to GitHub. At least in the meantime someone may make use of this.

It's currently a proof of concept. Depending on how much interest there is, I'll clean it up and not just have it workable.

Any pull requests are of course welcome.
